name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Mantener esto si es un proyecto privado

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_map: ^4.0.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  # Agrega esta línea
  multi_select_flutter: ^4.1.3
  latlong2: ^0.8.1
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0  # Add this explicitly
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.7+3
  intl: ^0.19.0  # Actualiza esta línea
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.14
  image_picker_for_web: ^2.0.0
  file_picker: ^5.0.0
  intl_phone_number_input: ^0.7.3+1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png

